#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-0 -d 1 2 3
bspc monitor HDMI-0 -d 4 5 6
bspc monitor HDMI-1 -d 7 8 9
xrandr --output HDMI-0 --mode 2560x1440 --pos 0x0 --rotate left --output DP-0 --primary --mode 2560x1440 --pos 1440x1120 --rotate normal --output DP-1 --off --output HDMI-1 --mode 1920x1080 --pos 4000x1300 --rotate normal


bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

nitrogen --restore
/home/error/.config/polybar/launch.sh

